### ISSUE TITLE
Add project to maven repository

### ISSUE THREAD

**Issue by Hervian** [Hervian/lambda-factory#4]
The pom should be modified and the project added to the maven repository.  
See http://central.sonatype.org/pages/requirements.html

**Comment by He-Pin** [comment]
+1 for this:)I am going to try this project out now.

**Comment by Hervian** [comment]
Thanks for your up votes of this issue, I aim at adding adding it to the maven repository during the coming week, where I have vacation.

**Comment by Infrag** [comment]
+1

**Comment by Citymonstret** [comment]
What happened to this? It'd be awesome to have it available on Maven Central. Right now the project is only accessible through JitPack.

**Comment by zhegexiaohuozi** [comment]
@Hervian I can not find in  maven central repository

**Comment by gajendravaradhan** [comment]
Is this project added to Maven Central yet? I see Hervian's comment  in 2016 about doing it in 2016

**Comment by Hervian** [comment]
It is in Maven Central now. 
Thanks for the patience. Let me know if you are experiencing any problems with the new java 9 modularized version.

**Comment by gajendravaradhan** [comment]
Thank you very much!
