### ISSUE TITLE
Access to private API functions (JDK 9+)

### ISSUE THREAD

**Issue by hrkalona** [Hervian/lambda-factory#9]
The code uses the hack that changes the value of the field "allowedModes". If you port this for jdk 9 you will get a warning (WARNING: An illegal reflective access operation has occurred....). Technically it still works, but it mentions that those accesses will be denied in future releases.

if you want to eliminate this hack you can use  the method "MethodHandles.privateLookupIn".

For example:

 public static <T> T createLambda(Method method, Class<T> interfaceClass, String signatatureName, boolean createSpecial) throws Throwable {

 MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(method.getDeclaringClass(), MethodHandles.lookup());
 return privateCreateLambda(method, lookup, interfaceClass, signatatureName, createSpecial);
		
 }

**Comment by SadiinsoSnowfall** [comment]
Thanks for the tip, it worked just fine on JDK 10.1 after that !

**Comment by Hervian** [comment]
Thanks for the tio - finally I got around to implement it.
